### ISSUE TITLE
Charla de diseño de componentes con react

### ISSUE THREAD

**Issue by Shinkei** [react-medellin/meetup#11]
# Me gustaría

- [ ] Ser el próximo speaker
- [x] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

## Descripción

Creo que la parte mas importante/difícil al momento de crear una aplicación con React en el diseño de la app y los componentes, estaría buena una charla con consejos y ejemplos  ó un ejercicio en vivo para que todos los sigamos.

**Comment by alejandronanez** [comment]
@Shinkei qué buena idea! Me parece un buen tema para alguien que quiera dar su primera charla ya que como lo veo no es tan complejo. Ya tengo experiencia en el tema así que podría ayudar a estructurarla si alguien se anima!

**Comment by shmesa22** [comment]
@alejandronanez Me gustaría hablar de este tema y además hablar un poco sobre las posibles estructuras de una aplicación. Podría llevar ejemplos de la vida real, mostrando un poco de la aplicación en la que estoy trabajando actualmente.

**Comment by alejandronanez** [comment]
Listo @shmesa22, agendado para Octubre 😎

Muchas gracias!!!
