### ISSUE TITLE
Workshop para crear componentes con los asistentes

### ISSUE THREAD

**Issue by Shinkei** [react-medellin/meetup#12]
# Me gustaría

- [ ] Ser el próximo speaker
- [x] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

## Descripción
Mas que mi propuesta anterior sobre el diseño, estaría genial poder tener un workshop para crear componentes básicos (Botones, inputs ... etc) guiados por los expositores, y repasar el proceso de creación de los componentes y la aplicación, lo mas simple posible, si meter ruido de otos temas (webpack por ejemplo):no_mouth:.

**Comment by facosta0787** [comment]
Seria muy bueno, por ejemplo podriamos usar nextjs y asi agilizar el proceso de codigo y ahorrarnos el tiempo de configuracion. Cuando lo hacemos ?

**Comment by alejandronanez** [comment]
Hola @Shinkei gracias por tu aporte! Suena súper interesante la propuesta!
Veamos qué acogida tiene para poder gestionar todo. Entre más gente interesada mejor.
Pienso que sería bueno con gente que solo tiene conocimientos en Javascript y poco o nada en React.

**Comment by alejandronanez** [comment]
@Shinkei listo! Vamos a hacer nuestro primer workshop el 12 de agosto! https://www.meetup.com/React-Medellin/events/241918753/

Gracias por tu idea!!!

**Comment by Shinkei** [comment]
Gracias @alejandronanez  :smile:
