### ISSUE TITLE
Testing de Componentes de React con Jest y Enzyme

### ISSUE THREAD

**Issue by juanda95** [react-medellin/meetup#15]
# Me gustaría

- [X] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

## Descripción

¡Hola comunidad! Mi nombre es Juan David y soy desarrollador full-stack en Ubidots.

Quisiera dar una charla sobre pruebas unitarias de componentes en React haciendo uso de Jest y Enzyme.
Las pruebas unitarias son un elemento realmente importante en las aplicaciones, pues nos permite verificar que el componente realmente hace lo que deseamos que haga, y nos permite verificar en cada nueva versión que el componente continua funcionando de la forma esperada.

¡Espero estén bien! 👍

**Comment by alejandronanez** [comment]
Hola @juanda95, gracias por tu interés en compartir con la comunidad.
Por ahora no tenemos un documento de guidelines _formal_ para la gente que quiera dar una charla (estoy trabajando en ello).  Pero la idea, es que envíes tus slides a alejonanez@gmail.com una semana antes del meetup. En cuánto a la fecha, @miguerp tendría el espacio de agosto entonces tu charla sería en el mes de agosto.

**Comment by alejandronanez** [comment]
@juanda95 te cuento que ya tenemos luz verde en RutaN para dar nuestras charlas hasta diciembre. Estaré creando los meetups pronto, vas para septiembre!

Gracias por tu interés en la comunidad!

**Comment by juanda95** [comment]
¡Perfecto! Muchísimas gracias. 😄
