### ISSUE TITLE
Charla + Workshop de MobX

### ISSUE THREAD

**Issue by thedull** [react-medellin/meetup#18]
# Me gustaría
- [X] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción

Quisiera postularme para dar una charla y un workshop sobre MobX. Yo mismo las di en MedellinJS, pero hay varias lecciones aprendidas que harán de éstas algo mejor.

FYI, [MobX](https://github.com/mobxjs/mobx) es una librería para el manejo del estado sin tanto *boilerplate* como el que se requiere en Redux, lo que lo hace una buena opción para el caso en que se una solución más simple y versátil.

**Comment by alejandronanez** [comment]
Muchas gracias @thedull! tenemos espacios libres desde octubre hasta diciembre. Si necesitas las dos horas del meetup no hay problema.
Quedamos atentos!!!
