### ISSUE TITLE
React router

### ISSUE THREAD

**Issue by alejandronanez** [react-medellin/meetup#25]
# Me gustaría
- [ ] Ser el próximo speaker
- [x] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción

React router es una pieza clave al momento de desarrollar un Single Page Application con React.
https://reacttraining.com/react-router/

**Comment by shmesa22** [comment]
Mi nombre es Simón Hoyos, y actualmente me encuentro trabajando para una compañía llamada Protalento como desarrollador FrontEnd, principalmente usando React. Al crecer una aplicación es fundamental saber utilizar React Router. Por esto quiero compartirles mis conocimientos de esta librería, ¿Cómo configurarlo?, ¿En qué se diferencia a otros enrutadores?, y más...
