### ISSUE TITLE
Server Side Render con React

### ISSUE THREAD

**Issue by facosta0787** [react-medellin/meetup#26]
# Me gustaría
- [ ] Ser el próximo speaker
- [x] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción

Server side render es importante para todas aquellas web que necesitan un buen SEO, y ademas para mejorar la experiencia de usuario al momento de la carga inicial de las paginas.

**Comment by williamegomezo** [comment]
Hola, 

En el mes de agosto me gustaría dar una de SSR con next.js o gatsby.js o inclusive comparandolos.

**Comment by simonhoyos** [comment]
@williamegomezo ya queda entonces esta charla para Agosto.

Bacano la comparación.

**Comment by alejandronanez** [comment]
@williamegomezo 👋 gracias por tu interés!

El equipo de Next.js anunció unos cambios MUY importantes a Next.js, acá está la charla de React Europe donde cuentan todo lo que se viene - depronto te sirve para la charla :)

https://www.youtube.com/watch?v=WKJVXN2kMS8

**Comment by williamegomezo** [comment]
Cool, gracias ñáñez!
