### ISSUE TITLE
React sin utilizar Create React App

### ISSUE THREAD

**Issue by alejandronanez** [react-medellin/meetup#29]
# Me gustaría
- [ ] Ser el próximo speaker
- [X] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Otro
## Descripción

Qué tal una charla donde expliquemos cómo crear un proyecto en React desde cero, sin necesidad de starter kits como [Create React App](https://github.com/facebookincubator/create-react-app)

**Comment by jramirezl** [comment]
Suena bien el tema!!! podría dar una parte

**Comment by alejandronanez** [comment]
Hola @jramirezl, a qué te refieres con una parte? 
Teníamos pensado una charla de entre 40-60 mins incluidas preguntas sobre este tema.

**Comment by jramirezl** [comment]
Hola @alejandronanez suena bien. Sera que te comento las ideas por pm o por aca ?

**Comment by simonhoyos** [comment]
I'd like to do a talk about this topic on August
