### ISSUE TITLE
Talk: CSS in JavaScript with JSS and React

### ISSUE THREAD

**Issue by romelperez** [react-medellin/meetup#40]
# Me gustaría

- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

### Charla

**CSS in JavaScript with JSS and React**

Implementar diseños para aplicaciones web es dificil. Aunque CSS con sus muchas herramientas provee una variedad de soluciones para crear estilos, persisten muchos problemas cuando los proyectos se vuelven más complejos o muchas personas comparten el mismo código. Bueno, algunas interesantes ideas han emergido para arreglar estos inconvenientes.

'CSS in JavaScript' es un poco disruptivo y mucha gente de la comunidad lo ve como una idea poco atractiva cuando CSS funciona. Vamos a ver cuáles son los problemas de CSS en escala, algunas soluciones del ecosistema de CSS, qué es JSS con React, sus ventajas y un par de herramientas para tu proyecto.

Duración: 45m
JSS: http://cssinjs.org
Artículo: https://medium.com/jobsity/css-in-javascript-with-jss-and-react-54cdd2720222

### Mis datos

RomelPerez.com
@romelperez
twitter.com/romelperez07

**Comment by alejandronanez** [comment]
Romel muchas gracias por tu interés!

Dos cosas:
- Tenemos espacio en el mes de Mayo. Te sirve?
- Quedamos pendientes de los slides una semana antes de la charla.

Gracias!

**Comment by romelperez** [comment]
Sí, para Mayo estaría perfecto!

Los slides ya los tengo, aunque espero hacer unas modificaciones.

Gracias.

**Comment by alejandronanez** [comment]
Súper, cuando los tengas listos puedes enviarlos a alejonanez@gmail.com / shmesa23@gmail.com / facosta0787@gmail.com 

Gracias!
