### ISSUE TITLE
Javascript Widgets completamente aislados usando Preact

### ISSUE THREAD

**Issue by elyalvarado** [react-medellin/meetup#42]
# Me gustaría
- [X] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
### Charla: Javascript Widgets completamente aislados usando Preact

Preact es una alternativa a React casi completamente compatible a nivel de API pero que ocupa solo 3Kb lo cual la hace un candidato perfecto para el desarrollo de Widgets en Javascript para ser distribuidos a páginas de 3ros.

En esta charla hablaré sobre como crear un Widget usando Preact:

- Como iniciar un proyecto en Preact para crear un widget
- Como incluir todos los recursos (css e imágenes) en el bundle
- Como hacer los widgets configurables por el usuario final

Duración aproximada: 30 min.

**Comment by alejandronanez** [comment]
Hola @elyalvarado, me gusta mucho el tema :)

Tenemos espacio libre para el meetup del 9 de Junio, qué te parece?

**Comment by elyalvarado** [comment]
Me parece bien, estaré preparando los slides y un artículo para compartirlo. En cuanto lo tenga listo se los envío para que me den su opinion

**Comment by alejandronanez** [comment]
Perfecto, quedamos pendientes @elyalvarado 

Gracias!
