### ISSUE TITLE
The Forgotten JavaScript

### ISSUE THREAD

**Issue by jonalvarezz** [react-medellin/meetup#44]
# Me gustaría
- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción
> React no está fallando. Es tú Javascript

Re descubramos conceptos fundamentales de JavaScript a través de funciones y Web APIs _olvidadas_ que nos mostrarán que algunas veces tal vez instalamos paquetes sin necesidad.

**Comment by alejandronanez** [comment]
Jonathan, nos gusta mucho el tema.

Cuándo puedes dar la charla?

**Comment by jonalvarezz** [comment]
Para Julio la podría dar.
