### ISSUE TITLE
react es simplemente javascript

### ISSUE THREAD

**Issue by camilomontoyau** [react-medellin/meetup#47]
# Me gustaría
- [x ] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción
Explicar cómo funcionan los cimientos de react, mostrar que no necesariamente necesitas una herramienta para crear bundles como webpack o parcel y que react no es tan fácil ni tan difícil cómo la gente cree que es. 

No olvides poner todos los detalles!

**Comment by alejandronanez** [comment]
Quedas agendado para el meetup de Noviembre @camilomontoyau, muchas gracias!
