### ISSUE TITLE
Testiando aplicaciones para react native 

### ISSUE THREAD

**Issue by maoapp** [react-medellin/meetup#48]
# Me gustaría
- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción
En esta charla explicaremos las diferentes herramientas para el testing de aplicaciones react navite ademas de ver las diferencias entre el testing web vs mobile en react.

**Comment by simonhoyos** [comment]
Hola @maoapp,

Gracias por postularte como speaker.

La charla ya la tienes lista?

**Comment by maoapp** [comment]
si parce

________________________________
De: Simon Hoyos <notifications@github.com>
Enviado: viernes, 17 de mayo de 2019 11:55
Para: react-medellin/meetup
Cc: MaoApp; Mention
Asunto: Re: [react-medellin/meetup] Testiando aplicaciones para react native (#48)


Hola @maoapp<https://github.com/maoapp>,

Gracias por postularte como speaker.

La charla ya la tienes lista?

**Comment by simonhoyos** [comment]
@maoapp te parece bien el Miércoles 10 de Julio? El Meetup seria de 6:00 pm a ~9:00pm
