### ISSUE TITLE
Server side rendering React Js + Asp.Net Core

### ISSUE THREAD

**Issue by devharf2310** [react-medellin/meetup#49]
# Me gustaría
- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción

Server side rendering es una feature cada vez más importante en las aplicaciones de React Js, en esta charla aprenderemos las generalidades de esta característica y mostraremos un ejemplo práctico de cómo hacerlo con ASP.Net Core.

**Comment by simonhoyos** [comment]
Hola @devharf2310,

Gracias por postularte como speaker y proponer este tema. Se ve muy interesante!

Por ahora tu charla quedaria para el Martes 13 de Agosto si te parece bien.

Estos horarios estan por confirmar dependiendo de las charlas pendientes. Te estaremos avisando cuando este todo confirmado.

Saludos!

**Comment by simonhoyos** [comment]
@devharf2310 podrías el Míercoles 12?

**Comment by devharf2310** [comment]
Hola @simonhoyos, si te refieres al 12 de Junio; claro que sí.

**Comment by simonhoyos** [comment]
Si 12 de Junio.

Perfecto, te agendo entonces

**Comment by simonhoyos** [comment]
@devharf2310 estás en slack? para terminar de coordinar?

**Comment by devharf2310** [comment]
Hola @simonhoyos , aún no estoy en el slack, me envías la invitación porfa.

**Comment by jmgr2996** [comment]
Hola @devharf2310 acabo de enviarte la invitación a tu correo de Github

**Comment by devharf2310** [comment]
Listo papá, ya estoy ahí.
