### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by alejandronanez** [react-medellin/meetup#6]
# Me gustaría

- [ ] Ser el próximo speaker
- [x] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

## Descripción

Qué tal hablar de React Native? Cómo funciona? Qué podemos hacer con él?

**Comment by apipemc** [comment]
✋🏼

**Comment by alejandronanez** [comment]
Súper @apipemc, hablemos por gitter para coordinar bien! ✊🏼

**Comment by alejandronanez** [comment]
@apipemc queremos tener un proceso un poco más organizado. Te parece si mencionas un poco más en detalle sobre lo que vas a hablar y un breve intro sobre quién eres, qué te gusta hacer, etc...?
Todo esto sirve para poder publicar el siguiente encuentro en meetup.com

**Comment by apipemc** [comment]
@alejandronanez claro. ya estaba organizando la informacion y slider.
para que lo echaras un vistazo.

**Comment by alejandronanez** [comment]
Excelente @apipemc!!!
