### ISSUE TITLE
Aprendiendo ReactJS a través del desarrollo de Juegos

### ISSUE THREAD

**Issue by Jorger** [react-medellin/meetup#64]
# Me gustaría
- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro
## Descripción

Hola, mi nombre es Jorge Rubiano, me gustaría proponer el tema relacionado al aprendizaje de ReactJS a través del desarrollo de juegos.

Algunos de los juegos son:

# El Parqués/parchis.

![parchis](https://res.cloudinary.com/practicaldev/image/fetch/s--2Y9PsfON--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://raw.githubusercontent.com/Jorger/parchisi-game/master/images_tutorial/img_01.gif%3Ftoken%3DAAAHKYVOA74X63ESLYE33CK6KP5AW)

* **Url del juego:** [https://parchisreact.herokuapp.com/](https://parchisreact.herokuapp.com/)
* **Artículo relacionado:** [https://dev.to/jorger/recreando-el-parques-parchis-en-reactjs-primera-parte-nkk](https://dev.to/jorger/recreando-el-parques-parchis-en-reactjs-primera-parte-nkk)

# Mr. Square

![parchis](https://res.cloudinary.com/practicaldev/image/fetch/s--_m0auwMG--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_66%2Cw_880/https://dev-to-uploads.s3.amazonaws.com/i/0htgudya8183xgghajal.gif)

* **Url del juego:** [https://mrsquare.herokuapp.com/](https://mrsquare.herokuapp.com/)
* **Artículo relacionado:** [https://dev.to/jorger/mr-square-en-reactjs-primera-parte-49eo](https://dev.to/jorger/mr-square-en-reactjs-primera-parte-49eo)

# Temas a tratar:

En esta charla me gustaría mostrar la forma en la que he aprendiendo [ReactJS](https://reactjs.org/), a través del desarrollo de Juegos, lo que ha ayudado a tener un mayor entendimiento del funcionamiento de está librería, los juegos van desde la creación de una [calculadora](https://calculator-game-reactjs.now.sh/) hasta el desarrollo de un [Parqués](https://parchisreact.herokuapp.com/) (juego en tiempo real), igualmente cada juego es [PWA](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps) por defecto lo que entrega una funcionalidad offline. Todos los juegos muestran la evolución de aprendizaje desde el manejo de componentes basados en [clases](https://reactjs.org/docs/components-and-props.html), hasta el uso de [hooks](https://reactjs.org/docs/hooks-intro.html).

Además el uso de librerías como es el caso de [react-spring](https://www.react-spring.io/) para el manejo de animaciones, en este caso utilizado para el juego [Mr. Square](https://mrsquare.herokuapp.com/)

Gracias por la atención prestada.

**Jorge Rubiano**
[@ostjh](https://twitter.com/ostjh)

**Comment by simonhoyos** [comment]
Hola @Jorger, 

Gracias por postularte para ser speaker.

Por ahora tenemos espacio para Noviembre, te parece bien? Igualmente tenemos varias charlas por confirmar entonces podría ser antes en caso que no podamos concretar alguna de esas charlas.

Saludos

**Comment by jrubianoHuge** [comment]
Hola @simonhoyos 

Claro que si, por mí esta bien esa fecha y pues si llegase a ser una fecha antes de Noviembre, por mi también está bien.

Muchas gracias por tener en cuenta está charla y espero ser parte del meetup en la fecha que se establezca.

Jorge Rubiano.

**Comment by Jorger** [comment]
Hola @simonhoyos 

Claro que si, por mí esta bien esa fecha y pues si llegase a ser una fecha antes de Noviembre, por mi también está bien.

Muchas gracias por tener en cuenta está charla y espero ser parte del meetup en la fecha que se establezca.

**Que pena, había escrito la respuesta con otra cuenta de github** 😞 

Jorge Rubiano.

**Comment by simonhoyos** [comment]
Listo, perfecto. Estamos en contacto entonces y te voy contando sobre los espacios

**Comment by simonhoyos** [comment]
Hola @Jorger, estamos organizando un evento para el Sábado 10 de Octubre a las 2:00 p.m. hora Colombia. Tu podrías y te gustaría dar tu charla ese día?

**Comment by Jorger** [comment]
Hola @simonhoyos claro que sí, yo podría dar la charla ese día a esa hora, muchas gracias por tenerla en cuenta, estaré atento a los detalles de cómo sería la transmisión.

Jorge Rubiano

**Comment by simonhoyos** [comment]
@Jorger vamos a crear una conversación con los dos expositores de ese día en twitter y ahí les explicamos todos los detalles

**Comment by Jorger** [comment]
Hola @simonhoyos listo muchas gracias, mi usuario en twitter es: [@ostjh](https://twitter.com/ostjh) hasta entonces 👍

**Comment by alejandronanez** [comment]
Excelente charla @Jorger. Gracias por aportar a la comunidad! 🙌
