### ISSUE TITLE
Testing en React (RTL edition)

### ISSUE THREAD

**Issue by d4vsanchez** [react-medellin/meetup#72]
# Me gustaría
- [x] Ser el próximo speaker
- [ ] Proponer un tema
- [ ] Dar mi retroalimentación
- [ ] Convertirme en organizador
- [ ] Otro

## Descripción

Hace unos años di una charla sobre Testing en React haciendo uso de Enzyme, y aunque esto aún funciona para lograr el resultado de hacer testing, hay varias cosas que se han convertido en anti-patterns.

La idea con esta charla es hablar con mas propiedad y demás temas actuales sobre:
- Buenas prácticas al realizar test en React.
- ¿Cómo hacer tests en React? Crear nuestra propia librería simple de testing.
- ¿Cómo hacer tests en React con Testing Library?.
- ¿Cómo probar componentes que hacen uso de HTTP Requests? (con `msw`).

La charla consistiría en una presentación al paralelo de ejemplos con código (Show me the code!).

**Comment by simonhoyos** [comment]
Hola @d4vsanchez, aún no tenemos fechas para el meetup este año. Apenas organicemos te escribo para confirmarte las fechas disponibles

**Comment by d4vsanchez** [comment]
No problem! Estaré pendiente de cualquier cosa, @simonhoyos. Muchísimas gracias por la respuesta!

**Comment by simonhoyos** [comment]
Hola @d4vsanchez, ya estuvimos coordinando y tenemos una fecha tentativa para empezar este año. Te quedaría bien el Jueves 18 de Febrero de 6:30pm a 7:00pm?

**Comment by d4vsanchez** [comment]
Sí, claro. Está bien ese día.

**Comment by simonhoyos** [comment]
Perfect, vamos a coordinar entonces y te vamos contando cualquier cosa
